
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 06 12:36:23 BRT 2015
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int error = 1;
  public static final int ANY = 2;
  public static final int EOF = 0;
}

